### ISSUE TITLE
Listing add extra Loading state?

### ISSUE THREAD

**Issue by JasonHezz** [xmartlabs/fountain#36]
For now , if I want ton know whether is loading more, fetch from refresh or network status seems unreasonable

**Comment by matir91** [comment]
Hi @JasonHezz Can you explain a bit more about how this would work?
Right now there are 2 separate status, one for the common network request (for example when fetching a new page) and another one  for the refresh status. If you want to combine both in a single `LiveData<NetworkState>` you can build an extension using a [`MediatorLiveData`](https://developer.android.com/reference/android/arch/lifecycle/MediatorLiveData). You can see an example of that [here](https://github.com/xmartlabs/fountain/blob/master/app/src/main/java/com/xmartlabs/sample/ui/ListUsersViewModel.kt#L22).

**Comment by JasonHezz** [comment]
Sorry, I should be more specific. Usually we want to add a progress bar as a footer in listview or recylerview to indicate that we are fetching next page.How do we know the status?  If I show the progress bar from network request (status is running), which will cause footer be showed in loadInitial.
Here is my workaround
```
data class Listing<T>(
   val networkState: LiveData<NetworkState>
   val refreshState: LiveData<NetworkState>
   val loadingMoreState: LiveData<NetworkState>
   ....
)
```

```
override fun loadAfter(params: LoadParams<Int>, callback: LoadCallback<Int, T>) {
    synchronized(this) {
      if (networkDataSourceAdapter.canFetch(page = params.key, pageSize = params.requestedLoadSize)
          && !isLoadingInitialData) {
        networkState.postValue(NetworkState.LOADING)
        loadingMoreState.postValue(NetworkState.LOADING)
        networkDataSourceAdapter.fetchPage(page = params.key, pageSize = params.requestedLoadSize)
            .subscribeOn(ioServiceExecutor)
            .subscribe(object : SingleObserver<ListResponse<T>> {
              override fun onSuccess(data: ListResponse<T>) {
                retry = null
                callback.onResult(data.getElements(), params.key + 1)
                networkState.postValue(NetworkState.LOADED)
                loadingMoreState.postValue(NetworkState.LOADED)
              }

              override fun onSubscribe(d: Disposable) {}

              override fun onError(t: Throwable) {
                retry = {
                  loadAfter(params, callback)
                }
                networkState.postValue(NetworkState.error(t))
                loadingMoreState.postValue(NetworkState.error(t))
              }
            })
      }
    }
  }
```

**Comment by matir91** [comment]
Yes, I think we can implement something like that. Maybe we can send the page number in the loading information. And then you can use that number to know if the library is loading the first page or not. Furthermore, we could add an extension to check that.
