### ISSUE TITLE
Does it work with realm data models? 

### ISSUE THREAD

**Issue by mhdtouban** [xmartlabs/fountain#51]

**Comment by matir91** [comment]
Hey, thanks for your contribution!

I haven't tried the Ream db in Fountain but I think you shouldn't have any problems.
I'm assuming that you want to integrate the second mode of Fountain, [`Cache + Network support`](https://github.com/xmartlabs/fountain#cache--network-support).

The [`NetworkDataSourceAdapter`](https://github.com/xmartlabs/fountain#network-support-for-paged-endpoints) is trivial, and the implementation will depend on what library are you using (`RxJava`, `Coroutine` or `Retrofit`) (you can check the sample app).

So, the hardest thing is the [`CachedDataSourceAdapter`](https://github.com/xmartlabs/fountain#cacheddatasourceadapter).
One of their methods, the `getDataSourceFactory()`, requires a `DataSource.Factory<*, DataSourceValue>`, so yo need to get if from a Realm database.

To do that you can use the [realm-monarchy](https://github.com/Zhuinden/realm-monarchy) library which is a wrapper that exposes `RealmResults` as various forms of `LiveData`. 
I haven't tried it, but it seems that it could be very useful for you!
If you don't like that library, there are other post in medium that tell you how you can get a  `DataSource.Factory` from a `Realm` db.

Please tell us if it worked for you.
I'll close the issue, but if it didn't work for you feel free to open it again!

**Comment by mhdtouban** [comment]
Thanks for your reply, I have tried realm-monarchy
<https://github.com/Zhuinden/realm-monarchy> with a custom paging setup
before to have it work. I thought you would support that straight out of
the box. For realm-monarchy, I don't like to have a different library to
manage the realm lifecycle the way it is. I guess unless realm has made
something to support paging we can't have a good solution there.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
11/05/18,
11:50:25 AM
