### ISSUE TITLE
Upgrade Coroutines to stable version

### ISSUE THREAD

**Issue by Glurt** [xmartlabs/fountain#52]
First of all, great library, it's gonna come in useful for my app so keep up the good work.

Now that Coroutines are in a stable state in Kotlin 1.3.0 it's probably worth updating from the experimental version. I'm assuming it's more than just updating the version number which is why I haven't attempted a PR myself.

**Comment by matir91** [comment]
Hey, thanks for your contribution!
Yes, it's in our roadmap to migrate Fountain to Kotlin 1.3.0 and it will be available shortly. The migration shouldn't be so hard because the library is currently using the latest Coroutine experimental version.
